_target_: federated_methods.ISP.ISP.ISP

base_method: fedavg # fedavg, fedcbs, delta, pow, fedcor

step_find_optimal: 20 # every step_find_optimal we will calculate optimal amount clients
num_samples: 10 # num of sampling clients when calculate optimal amount clients
sample_step: 1 # grid step when calculate optimal amount clients
num_clients_momentum: 0.5 # momentum to update optimal number of clients

warmup_rounds: 7 # amount of full communication rounds
window_sz_loss: 5 # size of window for average trust loss by history
local_epoch_on_wp: 3 # amount of local epoch on clients while warmup

args: null
